objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>IsProccessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsProccessed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JSON__c</fullName>
        <label>JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JSONToSobject.cls
global class JSONToSobject implements Database.Batchable<sobject>,Database.stateful
{
    
    String query = 'Select JSON__c, IsProccessed__c from Event__c where IsProccessed__c = false';
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
     {
        return Database.getQueryLocator(query);
     }
    global void execute(Database.BatchableContext BC, list<Event__c> events)
     {
        JSONToSobjectHandler.createRecordsBasedOnEvents(events);
        
     }
    global void finish(Database.batchableContext bc)
     {
        System.debug('Processing Completed...');
     }
    
}