objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Service_Fee__c</fullName>
        <label>Service Fee</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Tax</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Labour_Cost__c</fullName>
        <formula>Number_of_Labour__c  *  Labour_Cost_Per_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total_Labour_Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>( (Total_Labour_Cost__c  +  Service_Fee__c)  -  ((Total_Labour_Cost__c  +  Service_Fee__c)* Discount__c ) ) +  (( (Total_Labour_Cost__c  +  Service_Fee__c)  -  ((Total_Labour_Cost__c  +  Service_Fee__c)* Discount__c ) )* Tax__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AbcContainer.cls
public with sharing class AbcContainer {
    
    private Invoice__c invoiceContainer{get;set;}
   public Map<String,Double> mapExpenses{get;set;}
   public List<String> keyMap{get;set;}
   public AbcContainer (ApexPages.StandardController abc)
   {
       invoiceContainer = (Invoice__c)abc.getRecord();
       invoiceContainer = [SELECT Service_Fee__c,Total_Labour_Cost__c,Discount__c,Tax__c,Total__c FROM Invoice__c WHERE Id=:invoiceContainer.Id];
       mapExpenses = new Map<String,Double>();
       keyMap = new List<String>(); 
       System.debug('Invoice Info:::'+invoiceContainer);
       mapExpenses.put('Service Fee', invoiceContainer.Service_Fee__c);
       System.debug(':::After Service Fee');
       mapExpenses.put('Labour Cost', invoiceContainer.Total_Labour_Cost__c);
       System.debug(':::After Labour Cost');
       mapExpenses.put('Discount', invoiceContainer.Discount__c);
       System.debug(':::After Discount');
       mapExpenses.put('Tax', invoiceContainer.Tax__c);
       mapExpenses.put('Total', invoiceContainer.Total__c);
       keyMap.addAll(mapExpenses.keySet());
       System.debug('Map:::::'+mapExpenses);
   }
    
}