objects/LangCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>LangCode</label>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestStudentForm.cls
@isTest
private class TestStudentForm {
     
    @testSetup
    public static void createDataFactory() {
           
           list<LangCode__c> Language_List = new list <LangCode__c>();
           LangCode__c record1 = new LangCode__c();
           record1.Name = 'English';
           record1.code__c = 'en';
           Language_List.add(record1);
           LangCode__c record2 = new LangCode__c();
           record2.Name = 'French';
           record2.code__c = 'fr';
           Language_List.add(record2);
           LangCode__c record3 = new LangCode__c();
           record3.Name = 'Spanish';
           record3.code__c = 'es';
           Language_List.add(record3);
           insert Language_List;

   }

   static testMethod void testFunctionality() 
   {
       
       Student__c s=new Student__c();   
       ApexPages.StandardController sc = new ApexPages.standardController(s);
       StudentForm obj= new StudentForm(sc);
       
       Test.StartTest();
       System.debug('*************'+obj);
      
       obj.translation = 'Spanish';
       obj.changeLanguage();
       System.debug('*************'+obj);
       System.assertEquals('es', obj.lang);
       
       obj.translation = 'French';
       obj.changeLanguage();
       System.debug('*************'+obj+obj.lang);
       System.assertEquals('fr', obj.lang);
       
       obj.translation = 'English';
       obj.changeLanguage();
       System.debug('*************'+obj+obj.lang);
       Test.StopTest();
       System.assertEquals('en', obj.lang);
   }
   
   static testMethod void saveTest()
   {
       test.startTest();
       Student__c st=new Student__c(Name='New Test',Roll_Number__c=76,Gender__c='Female');
       ApexPages.StandardController sc = new ApexPages.standardController(st);
       StudentForm obj= new StudentForm(sc);
           
           Test.setCurrentPage(Page.StudentForm);
           obj.translation = 'English';
           obj.changeLanguage();
           System.debug(obj);
           
           obj.submitPage();
           List<Apexpages.Message> msgs = ApexPages.getMessages();
            
            
            
            for(Apexpages.Message msg : msgs)
            {
              String successMsg=msg.getDetail();
                system.assertEquals('Record Added Successfully',successMsg);
                System.debug(successMsg);
                
                test.stopTest();
            }
   }
}